export const SEARCH_REPOSITORIES = 'HomePage/SEARCH_REPOSITORIES';
export const SEARCH_REPOSITORIES_FAILED = 'HomePage/SEARCH_REPOSITORIES_FAILED';
export const SEARCH_REPOSITORIES_COMPLETE = 'HomePage/SEARCH_REPOSITORIES_COMPLETE';

export const searchRepositories = () => ({ type: SEARCH_REPOSITORIES });
